import { MigrationInterface, QueryRunner } from "typeorm";

export class PrimeraMigracion1732113202861 implements MigrationInterface {
    name = 'PrimeraMigracion1732113202861'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "fase" ("IdFase" number GENERATED BY DEFAULT AS IDENTITY, "NombreFase" varchar2(255) NOT NULL, CONSTRAINT "PK_ac4b28cfdbb273fb6895e44f3e6" PRIMARY KEY ("IdFase"))`);
        await queryRunner.query(`CREATE TABLE "proyecto" ("IdProyecto" number GENERATED BY DEFAULT AS IDENTITY, "NombreProyecto" varchar2(255) NOT NULL, "Descripcion" varchar2(255) NOT NULL, "TiempoInicio" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "TiempoFinalizacion" timestamp NOT NULL, "IdFase" number, CONSTRAINT "PK_444f9e03bbb28ce7e0976c04d3e" PRIMARY KEY ("IdProyecto"))`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18" FOREIGN KEY ("IdFase") REFERENCES "fase" ("IdFase")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18"`);
        await queryRunner.query(`DROP TABLE "proyecto"`);
        await queryRunner.query(`DROP TABLE "fase"`);
    }
}
