import { MigrationInterface, QueryRunner } from "typeorm";

export class Quinta1732125628133 implements MigrationInterface {
    name = 'Quinta1732125628133'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18"`);
        await queryRunner.query(`CREATE TABLE "lider" ("cedula" number GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar2(50) NOT NULL, "contrasenia" varchar2(16) NOT NULL, "rol" number DEFAULT 3 NOT NULL, CONSTRAINT "PK_16b3f2daa019cf903c7eaedcd3f" PRIMARY KEY ("cedula"))`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "UQ_25363e0f0b97ff0e5c91b741b18"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "IdFase"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "Estado" number DEFAULT 0 NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "IdLider" number`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "UQ_01f8df39316c7476d0ee2e6ffd7" UNIQUE ("IdLider")`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_01f8df39316c7476d0ee2e6ffd7" FOREIGN KEY ("IdLider") REFERENCES "lider" ("cedula") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_01f8df39316c7476d0ee2e6ffd7"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "UQ_01f8df39316c7476d0ee2e6ffd7"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "IdLider"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "Estado"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "IdFase" number`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "UQ_25363e0f0b97ff0e5c91b741b18" UNIQUE ("IdFase")`);
        await queryRunner.query(`DROP TABLE "lider"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18" FOREIGN KEY ("IdFase") REFERENCES "fase" ("IdFase")`);
    }

}
