import { MigrationInterface, QueryRunner } from "typeorm";

export class Tercera1732122051081 implements MigrationInterface {
    name = 'Tercera1732122051081'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "persona" ("cedula" number GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar2(50) NOT NULL, "contrasenia" varchar2(16) NOT NULL, "rol" number DEFAULT 3 NOT NULL, CONSTRAINT "PK_16a022deecdae1ee0872e3baf6a" PRIMARY KEY ("cedula"))`);
        await queryRunner.query(`CREATE TABLE "docente" ("cedula" number GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar2(50) NOT NULL, "contrasenia" varchar2(16) NOT NULL, "rol" number DEFAULT 3 NOT NULL, CONSTRAINT "PK_ec0413e8301ffcdb03e269ac254" PRIMARY KEY ("cedula"))`);
        await queryRunner.query(`CREATE TABLE "director" ("cedula" number GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar2(50) NOT NULL, "contrasenia" varchar2(16) NOT NULL, "rol" number DEFAULT 3 NOT NULL, CONSTRAINT "PK_e39174e58a05ccda83a414824f2" PRIMARY KEY ("cedula"))`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "IdDocente" number`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "UQ_25363e0f0b97ff0e5c91b741b18" UNIQUE ("IdFase")`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18" FOREIGN KEY ("IdFase") REFERENCES "fase" ("IdFase")`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_0b5af349840abdb971251d0e45e" FOREIGN KEY ("IdDocente") REFERENCES "docente" ("cedula")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_0b5af349840abdb971251d0e45e"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "UQ_25363e0f0b97ff0e5c91b741b18"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_25363e0f0b97ff0e5c91b741b18" FOREIGN KEY ("IdFase") REFERENCES "fase" ("IdFase")`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "IdDocente"`);
        await queryRunner.query(`DROP TABLE "director"`);
        await queryRunner.query(`DROP TABLE "docente"`);
        await queryRunner.query(`DROP TABLE "persona"`);
    }

}
